//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kindergarten_app.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genders
    {
        public Genders()
        {
            this.Kid = new HashSet<Kid>();
            this.Parent = new HashSet<Parent>();
            this.Workers = new HashSet<Workers>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Kid> Kid { get; set; }
        public virtual ICollection<Parent> Parent { get; set; }
        public virtual ICollection<Workers> Workers { get; set; }
    }
}
