//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kindergarten_app.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public Workers()
        {
            this.PrivateLessons = new HashSet<PrivateLessons>();
        }
    
        public int Id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Patronimyc { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
        public string DateOfBirth { get; set; }
        public string PassportNumber { get; set; }
        public int RoleId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool IsValid { get; set; }
    
        public virtual ICollection<PrivateLessons> PrivateLessons { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
